version: "3.8"

volumes:
    postgres_data: {}

services:
    fastapi:
        container_name: monster-spawner-api
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: dev
        env_file:
            - ./docker/.env
        volumes:
            - .:/app
        ports:
            - 8002:8002
        depends_on:
            - postgres
        stdin_open: true
        tty: true

    postgres:
        container_name: monster-spawner-db
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=monster-spawner
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
